name: Run tests
on:
    pull_request:
        branches: [master]

jobs:
    build:
        # In use: Heroku-18 stack (Ubuntu 18.04)
        runs-on: ubuntu-18.04

        steps:
            - uses: actions/checkout@v2
            - name: npm test w/ node 16
              uses: actions/setup-node@v2
              with:
                  node-version: 16
            - name: Install dependencies
              run: npm ci
            - run: npm run build --if-present
            - run: npm test
